spring.application.name=auth
server.port=8080

# URL de conexión a tu base de datos (cambia 'ecommerce_db' por el nombre de tu BD)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
# Pon aquí la contraseña que configuraste al instalar PostgreSQL
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
